### ISSUE TITLE
Could not open connection while creating document

### ISSUE THREAD

**Issue by bgold0** [PHP-on-Couch/PHP-on-Couch#33]
For some reason, I'm getting this strange error.

    $CLOUDANT_URL = "https://".$CLOUDANT_USERNAME.":".$CLOUDANT_PASSWORD."@".$CLOUDANT_HOST;
	
    $accountsClient = new CouchClient($CLOUDANT_URL, "accounts");

	Fatal error: Uncaught exception 'Exception' with message 'Could not open connection to XXXXX.cloudant.com:80: (0)' in /../vendor/popojargo/php-on-couch/src/Couch.php:446 
	Stack trace: #0 /../vendor/popojargo/php-on-couch/src/Couch.php(302): PHPOnCouch\Couch->_connect() 
	#1 /.../vendor/popojargo/php-on-couch/src/Couch.php(171): PHPOnCouch\Couch->_socket_query('POST', '/accounts', Array, Object(stdClass), NULL) 
	#2 /.../vendor/popojargo/php-on-couch/src/CouchClient.php(162): PHPOnCouch\Couch->query('POST', '/accounts', Array, Object(stdClass), NULL) 
	#3 /.../vendor/popojargo/php-on-couch/src/CouchClient.php(582): PHPOnCouch\CouchClient->_queryAndTest('POST', '/accounts', Array, Array, Object(stdClass)) in /.../vendor/popojargo/php-on-couch/src/Couch.php on line 446

With this code:

	//create the account without the "u"
	$doc = new CouchDocument($accountsClient);
	$doc->set(array("TEST" => "TEST"));
	$new_user_id = $doc->id();

I'm not really sure what's going on with the errors or what it is trying to tell me.

**Comment by bgold0** [comment]
Sorry, curl wasn't enabled.
