### ISSUE TITLE
Exception when adding first usermember to a database

### ISSUE THREAD

**Issue by fluffis** [PHP-on-Couch/PHP-on-Couch#85]
Hi,

I've discovered that the following scenario throws an exception:
* couchdb 3.1.0
* PHP-on-Couch 3.0.1
* PHP 7.4.3

I have a new server and want to add my first member to all current databases. The following code is used:
```
$client = new CouchClient('http://admin:password@127.0.0.1:5984', 'test');
$dbs = $client->listDatabases();
foreach($dbs as $dbname) {
    if(preg_match('/^\_/', $dbname))
        continue;

    echo "Db: {$dbname}\n";
    $client->useDatabase($dbname);
    $ca = new \PHPOnCouch\CouchAdmin($client);
    $ca->addDatabaseMemberUser("myuser");
}
```

The following exception is thrown:
```
PHP Notice:  Undefined property: stdClass::$names in /home/fluff/git/spider/vendor/php-on-couch/php-on-couch/src/CouchAdmin.php on line 458
PHP Stack trace:
PHP   1. {main}() /home/fluff/git/spider/test.php:0
PHP   2. PHPOnCouch\CouchAdmin->addDatabaseMemberUser() /home/fluff/git/spider/test.php:18
PHP Warning:  in_array() expects parameter 2 to be array, null given in /home/fluff/git/spider/vendor/php-on-couch/php-on-couch/src/CouchAdmin.php on line 458
PHP Stack trace:
PHP   1. {main}() /home/fluff/git/spider/test.php:0
PHP   2. PHPOnCouch\CouchAdmin->addDatabaseMemberUser() /home/fluff/git/spider/test.php:18
PHP   3. in_array() /home/fluff/git/spider/vendor/php-on-couch/php-on-couch/src/CouchAdmin.php:458
PHP Warning:  array_push() expects parameter 1 to be array, null given in /home/fluff/git/spider/vendor/php-on-couch/php-on-couch/src/CouchAdmin.php on line 461
PHP Stack trace:
PHP   1. {main}() /home/fluff/git/spider/test.php:0
PHP   2. PHPOnCouch\CouchAdmin->addDatabaseMemberUser() /home/fluff/git/spider/test.php:18
PHP   3. array_push() /home/fluff/git/spider/vendor/php-on-couch/php-on-couch/src/CouchAdmin.php:461
PHP Fatal error:  Uncaught PHPOnCouch\Exceptions\CouchException: Internal Server Error - no_majority in /home/fluff/git/spider/vendor/php-on-couch/php-on-couch/src/CouchAdmin.php:442
Stack trace:
#0 /home/fluff/git/spider/vendor/php-on-couch/php-on-couch/src/CouchAdmin.php(462): PHPOnCouch\CouchAdmin->setSecurity()
#1 /home/fluff/git/spider/test.php(18): PHPOnCouch\CouchAdmin->addDatabaseMemberUser()
#2 {main}
  thrown in /home/fluff/git/spider/vendor/php-on-couch/php-on-couch/src/CouchAdmin.php on line 442
```

This is due to the fact that the `_security` document lacks the property `names` when no member users (the same error for admin users) exists. Inspecting the _security document with getSecurity() verifies this:
```
stdClass Object
(
    [members] => stdClass Object
        (
            [roles] => Array
                (
                    [0] => _admin
                )

        )

    [admins] => stdClass Object
        (
            [roles] => Array
                (
                    [0] => _admin
                )

        )

)

```
Creating a PR for this. I don't know if an empty role property ever happens, but might be worth looking into.

**Comment by popojargo** [comment]
Fixed with #87
